import { motion } from 'framer-motion';
import { FileText, Download, Printer, AlertCircle, CheckCircle, Info, Brain } from 'lucide-react';
import { useAnalysis } from '../context/AnalysisContext';
import { Link } from 'react-router-dom';

export default function Reports() {
    const { result } = useAnalysis();

    // Empty state
    if (!result) {
        return (
            <div className="space-y-6">
                <div>
                    <h2 className="text-3xl font-bold text-white tracking-tight">Generated Report</h2>
                    <p className="text-gray-400 mt-1">Evidence-grounded radiology report with uncertainty awareness.</p>
                </div>
                <div className="flex flex-col items-center justify-center py-20 text-center">
                    <div className="w-20 h-20 rounded-2xl bg-indigo-500/10 flex items-center justify-center mb-6">
                        <FileText className="w-10 h-10 text-indigo-400/50" />
                    </div>
                    <h3 className="text-xl font-semibold text-white mb-2">No Report Generated</h3>
                    <p className="text-gray-400 mb-6 max-w-md">
                        Upload and analyze a chest X-ray first to generate a radiology report.
                    </p>
                    <Link
                        to="/upload"
                        className="px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-medium transition-all"
                    >
                        Go to Upload
                    </Link>
                </div>
            </div>
        );
    }

    // Parse report sections
    const reportText = result.report;
    const findingsMatch = reportText.match(/FINDINGS[:\s]*([\s\S]*?)(?=IMPRESSION|$)/i);
    const impressionMatch = reportText.match(/IMPRESSION[:\s]*([\s\S]*?)$/i);
    const findings = findingsMatch?.[1]?.trim() || '';
    const impression = impressionMatch?.[1]?.trim() || '';
    const hasStructuredReport = findings || impression;

    const handlePrint = () => {
        const printWindow = window.open('', '_blank');
        if (printWindow) {
            printWindow.document.write(`
                <html>
                <head><title>Radiology Report</title>
                <style>
                    body { font-family: 'Times New Roman', serif; padding: 40px; max-width: 700px; margin: 0 auto; }
                    h1 { font-size: 18px; border-bottom: 2px solid #000; padding-bottom: 10px; }
                    h2 { font-size: 14px; margin-top: 20px; text-transform: uppercase; letter-spacing: 1px; }
                    p { font-size: 13px; line-height: 1.8; }
                    .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin: 20px 0; font-size: 12px; }
                    .meta span { color: #666; }
                    .warning { background: #fff3cd; border: 1px solid #ffc107; padding: 10px; margin-top: 20px; font-size: 12px; }
                </style>
                </head>
                <body>
                    <h1>AI-Generated Radiology Report</h1>
                    <div class="meta">
                        <div><span>Prediction:</span> ${result.prediction}</div>
                        <div><span>Confidence:</span> ${(result.confidence * 100).toFixed(1)}%</div>
                        <div><span>Evidence Cases:</span> ${result.evidence.length}</div>
                        <div><span>Agreement:</span> ${result.disagreement ? 'Disagreement Detected' : 'Consensus'}</div>
                    </div>
                    <h2>Report</h2>
                    <p>${reportText.replace(/\n/g, '<br>')}</p>
                    ${result.disagreement ? '<div class="warning">⚠️ Disagreement was detected among retrieved evidence cases. Clinical correlation is recommended.</div>' : ''}
                    <p style="margin-top: 40px; font-size: 11px; color: #999;">
                        Generated by AI — For research and educational use only. Not a substitute for professional medical diagnosis.
                    </p>
                </body>
                </html>
            `);
            printWindow.document.close();
            printWindow.print();
        }
    };

    const handleExport = () => {
        const content = `RADIOLOGY REPORT
================

Prediction: ${result.prediction}
Confidence: ${(result.confidence * 100).toFixed(1)}%
Evidence Cases: ${result.evidence.length}
Keywords: ${result.keywords.join(', ')}
Agreement: ${result.disagreement ? 'Disagreement Detected' : 'Consensus'}

---

${reportText}

---

${result.disagreement ? 'WARNING: Disagreement was detected among retrieved evidence cases.\n' : ''}
Generated by AI — For research and educational use only.
`;
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `radiology_report_${result.prediction.toLowerCase()}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-start">
                <div>
                    <h2 className="text-3xl font-bold text-white tracking-tight">Generated Report</h2>
                    <p className="text-gray-400 mt-1">Evidence-grounded radiology report with uncertainty awareness.</p>
                </div>
                <div className="flex gap-2">
                    <button
                        onClick={handlePrint}
                        className="flex items-center gap-2 px-4 py-2 rounded-xl bg-white/5 border border-white/10 text-gray-300 hover:bg-white/10 transition-all"
                    >
                        <Printer className="w-4 h-4" />
                        Print
                    </button>
                    <button
                        onClick={handleExport}
                        className="flex items-center gap-2 px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white transition-all"
                    >
                        <Download className="w-4 h-4" />
                        Export
                    </button>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Main Report */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="lg:col-span-2 bg-white/5 border border-white/10 rounded-2xl overflow-hidden"
                >
                    {/* Header */}
                    <div className="bg-gradient-to-r from-indigo-500/10 to-purple-500/10 border-b border-white/10 p-6">
                        <div className="flex items-start justify-between">
                            <div className="flex items-center gap-3">
                                <div className="p-2 bg-indigo-500/20 rounded-lg">
                                    <FileText className="w-6 h-6 text-indigo-400" />
                                </div>
                                <div>
                                    <h3 className="text-lg font-semibold text-white">Radiology Report</h3>
                                    <p className="text-sm text-gray-400">AI-Generated, Evidence-Grounded</p>
                                </div>
                            </div>
                            <span className="flex items-center gap-1 text-xs bg-emerald-500/20 text-emerald-400 px-2 py-1 rounded-full">
                                <CheckCircle className="w-3 h-3" /> Generated
                            </span>
                        </div>
                    </div>

                    {/* Metadata */}
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-6 border-b border-white/10 bg-black/20">
                        <div>
                            <p className="text-xs text-gray-500 uppercase tracking-wider">Prediction</p>
                            <p className="text-sm font-medium text-white">{result.prediction}</p>
                        </div>
                        <div>
                            <p className="text-xs text-gray-500 uppercase tracking-wider">Confidence</p>
                            <p className="text-sm font-medium text-emerald-400">{(result.confidence * 100).toFixed(1)}%</p>
                        </div>
                        <div>
                            <p className="text-xs text-gray-500 uppercase tracking-wider">Evidence</p>
                            <p className="text-sm font-medium text-white">{result.evidence.length} cases</p>
                        </div>
                        <div>
                            <p className="text-xs text-gray-500 uppercase tracking-wider">Keywords</p>
                            <p className="text-sm font-medium text-indigo-400">{result.keywords.join(', ')}</p>
                        </div>
                    </div>

                    {/* Report Body */}
                    <div className="p-6 space-y-6">
                        {hasStructuredReport ? (
                            <>
                                {findings && (
                                    <div>
                                        <h4 className="text-xs font-semibold text-indigo-400 uppercase tracking-wider mb-3">Findings</h4>
                                        <p className="text-gray-200 leading-relaxed whitespace-pre-wrap">{findings}</p>
                                    </div>
                                )}
                                {impression && (
                                    <div>
                                        <h4 className="text-xs font-semibold text-indigo-400 uppercase tracking-wider mb-3">Impression</h4>
                                        <p className="text-white font-medium text-lg whitespace-pre-wrap">{impression}</p>
                                    </div>
                                )}
                            </>
                        ) : (
                            <div>
                                <h4 className="text-xs font-semibold text-indigo-400 uppercase tracking-wider mb-3">Report</h4>
                                <p className="text-gray-200 leading-relaxed whitespace-pre-wrap">{reportText}</p>
                            </div>
                        )}

                        {/* Disagreement Note */}
                        {result.disagreement && (
                            <div className="bg-amber-500/10 border border-amber-500/20 rounded-xl p-4">
                                <div className="flex items-start gap-3">
                                    <AlertCircle className="w-5 h-5 text-amber-400 mt-0.5 flex-shrink-0" />
                                    <div>
                                        <h4 className="font-semibold text-amber-300 mb-1">Disagreement Detected</h4>
                                        <p className="text-sm text-amber-200/70">
                                            Retrieved evidence cases showed disagreement. The generated report reflects the majority finding,
                                            but clinical correlation is recommended.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>
                </motion.div>

                {/* Sidebar */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.1 }}
                    className="space-y-4"
                >
                    {/* Prediction Summary */}
                    <div className="bg-white/5 border border-white/10 rounded-2xl p-5">
                        <h4 className="text-sm font-semibold text-white mb-4 flex items-center gap-2">
                            <Brain className="w-4 h-4 text-indigo-400" />
                            CNN Prediction
                        </h4>
                        <div className="space-y-3">
                            <div className="text-center py-4 bg-gradient-to-br from-indigo-500/10 to-purple-500/10 rounded-xl">
                                <p className="text-3xl font-bold text-white">{result.prediction}</p>
                                <p className="text-sm text-gray-400 mt-1">{(result.confidence * 100).toFixed(1)}% confidence</p>
                            </div>
                            <div className="h-2 bg-white/5 rounded-full overflow-hidden">
                                <motion.div
                                    initial={{ width: 0 }}
                                    animate={{ width: `${result.confidence * 100}%` }}
                                    transition={{ duration: 1, delay: 0.3 }}
                                    className="h-full bg-gradient-to-r from-indigo-500 to-emerald-500 rounded-full"
                                />
                            </div>
                        </div>
                    </div>

                    {/* Evidence Summary */}
                    <div className="bg-white/5 border border-white/10 rounded-2xl p-5">
                        <h4 className="text-sm font-semibold text-white mb-4 flex items-center gap-2">
                            <Info className="w-4 h-4 text-indigo-400" />
                            Evidence Summary
                        </h4>
                        <div className="space-y-2">
                            <div className="flex justify-between text-sm">
                                <span className="text-gray-400">Evidence cases</span>
                                <span className="text-white font-semibold">{result.evidence.length}</span>
                            </div>
                            <div className="flex justify-between text-sm">
                                <span className="text-gray-400">Top keywords</span>
                                <span className="text-indigo-400 font-semibold">{result.keywords.slice(0, 2).join(', ')}</span>
                            </div>
                            <div className="flex justify-between text-sm">
                                <span className="text-gray-400">Agreement</span>
                                <span className={`font-semibold ${result.disagreement ? 'text-amber-400' : 'text-emerald-400'}`}>
                                    {result.disagreement ? 'Disagreement' : 'Consensus'}
                                </span>
                            </div>
                        </div>
                    </div>

                    {/* Quick Actions */}
                    <div className="bg-white/5 border border-white/10 rounded-2xl p-5">
                        <h4 className="text-sm font-semibold text-white mb-4">Navigate</h4>
                        <div className="space-y-2">
                            <Link to="/evidence" className="w-full flex items-center justify-between p-3 rounded-xl bg-white/5 hover:bg-white/10 transition-all text-sm text-gray-300">
                                <span>View Evidence Cases</span>
                                <span className="text-xs text-indigo-400">{result.evidence.length} cases →</span>
                            </Link>
                            <Link to="/disagreement" className="w-full flex items-center justify-between p-3 rounded-xl bg-white/5 hover:bg-white/10 transition-all text-sm text-gray-300">
                                <span>Disagreement Analysis</span>
                                <span className="text-xs text-indigo-400">→</span>
                            </Link>
                            <Link to="/upload" className="w-full flex items-center justify-between p-3 rounded-xl bg-white/5 hover:bg-white/10 transition-all text-sm text-gray-300">
                                <span>New Analysis</span>
                                <span className="text-xs text-indigo-400">→</span>
                            </Link>
                        </div>
                    </div>
                </motion.div>
            </div>
        </div>
    );
}
